"""persistence — Postgres schema, RLS, migrations. See ``docs/LLD/persistence.md``.

The bottom layer: this module depends on no other module in the repository and every other
module depends on it. `[persistence.md §8]`

What `T0.5` lands is the schema and the boundary around it — the `MetaData` that is the single
definition of the tables, the row-level security policy and the audit that gates it, the
expand/contract lint that runs against the SQL a migration actually emits, and the
tenant-scoped session that is the only place `app.tenant_id` is ever set.

`T0.6` adds the rest of the bottom layer: the typed Redis key registry and the client that
refuses to write a key without the TTL that registry documents, the `jobs:stream` consumer-group
queue whose delivery is at-least-once by decision `[D-67]`, the artifact store with its
tenant-prefixed layout and SHA-256 verification, and presigned-URL minting that is never stored,
cached or logged `[D-52]`.

Nothing outside this package constructs an engine or a session. That is enforced by
`tests/unit/test_persistence_boundary.py` rather than asked for in a review, because a
connection opened elsewhere is a connection with no tenant scope on it.
"""

from video_agent.persistence.enums import (
    ARTIFACT_KIND,
    ATTEMPT_STATE,
    BEAT_KIND,
    ENUM_TYPES,
    JOB_OUTCOME,
    JOB_STATUS,
    SHOT_STATUS,
    ArtifactKind,
    AttemptState,
    BeatKind,
    JobOutcome,
    JobStatus,
    ShotStatus,
    enum_labels,
)
from video_agent.persistence.keys import (
    KEY_CONSTRUCTORS,
    KEY_REGISTRY,
    REGISTERED_PREFIXES,
    KeyName,
    KeySegmentError,
    KeySpec,
    MissingTtlError,
    RedisKey,
    RedisType,
    TtlPolicy,
    circuit_breaker_key,
    failure_signature_key,
    idempotency_key,
    job_lock_key,
    jobs_stream_key,
    llm_cache_key,
    progress_key,
    rate_limit_key,
    spec_for,
)
from video_agent.persistence.migration_lint import (
    LintFinding,
    MigrationLintError,
    Phase,
    lint_migration_script,
    lint_statements,
    parse_phase,
    split_statements,
)
from video_agent.persistence.objects import (
    ArtifactStore,
    ArtifactStoreError,
    ChecksumMismatchError,
    ObjectTransport,
    S3ObjectTransport,
    StorageKeyError,
    StoredObject,
    create_artifact_store,
    create_s3_client,
    sha256_of,
    storage_key,
    tenant_of,
)
from video_agent.persistence.presign import (
    PRESIGN_FAILURE_ALARM,
    ArtifactUrl,
    PresignFailedError,
    UrlMinter,
    mint_all,
    mint_artifact_url,
    mint_or_null,
    presign_ttl,
)
from video_agent.persistence.queue import (
    CONSUMER_GROUP,
    Delivery,
    JobMessage,
    JobQueue,
    MalformedQueueMessageError,
    QueueUnavailableError,
    queue_from_settings,
)
from video_agent.persistence.redis_client import (
    MissingKeyTtlError,
    RedisCommands,
    RedisStore,
    RedisUnavailableError,
    create_redis_client,
    create_redis_store,
    require_ttl,
)
from video_agent.persistence.repositories import (
    ArtifactRepository,
    AttemptClaim,
    CheckpointRepository,
    ContinuityBibleRepository,
    IdempotencyKeyReusedError,
    JobRepository,
    ShotAttemptRepository,
    ShotRepository,
    StoryPlanRepository,
)
from video_agent.persistence.rls import (
    APPLICATION_ROLE,
    RLS_EXEMPT_TABLES,
    RLS_EXEMPTION_REASONS,
    RLS_PROTECTED_TABLES,
    TENANT_SETTING,
    PolicyFacts,
    RlsViolation,
    TableRlsFacts,
    audit_rls,
)
from video_agent.persistence.schema import ALL_TABLES, TABLE_NAMES, metadata
from video_agent.persistence.session import (
    UNSET_TENANT_CONTEXT_ALARM,
    TenantContextMissingError,
    TenantSession,
    create_database_engine,
    tenant_session,
)

__all__ = [
    "ALL_TABLES",
    "APPLICATION_ROLE",
    "ARTIFACT_KIND",
    "ATTEMPT_STATE",
    "BEAT_KIND",
    "CONSUMER_GROUP",
    "ENUM_TYPES",
    "JOB_OUTCOME",
    "JOB_STATUS",
    "KEY_CONSTRUCTORS",
    "KEY_REGISTRY",
    "PRESIGN_FAILURE_ALARM",
    "REGISTERED_PREFIXES",
    "RLS_EXEMPTION_REASONS",
    "RLS_EXEMPT_TABLES",
    "RLS_PROTECTED_TABLES",
    "SHOT_STATUS",
    "TABLE_NAMES",
    "TENANT_SETTING",
    "UNSET_TENANT_CONTEXT_ALARM",
    "ArtifactKind",
    "ArtifactRepository",
    "ArtifactStore",
    "ArtifactStoreError",
    "ArtifactUrl",
    "AttemptClaim",
    "AttemptState",
    "BeatKind",
    "CheckpointRepository",
    "ChecksumMismatchError",
    "ContinuityBibleRepository",
    "Delivery",
    "IdempotencyKeyReusedError",
    "JobMessage",
    "JobOutcome",
    "JobQueue",
    "JobRepository",
    "JobStatus",
    "KeyName",
    "KeySegmentError",
    "KeySpec",
    "LintFinding",
    "MalformedQueueMessageError",
    "MigrationLintError",
    "MissingKeyTtlError",
    "MissingTtlError",
    "ObjectTransport",
    "Phase",
    "PolicyFacts",
    "PresignFailedError",
    "QueueUnavailableError",
    "RedisCommands",
    "RedisKey",
    "RedisStore",
    "RedisType",
    "RedisUnavailableError",
    "RlsViolation",
    "S3ObjectTransport",
    "ShotAttemptRepository",
    "ShotRepository",
    "ShotStatus",
    "StorageKeyError",
    "StoredObject",
    "StoryPlanRepository",
    "TableRlsFacts",
    "TenantContextMissingError",
    "TenantSession",
    "TtlPolicy",
    "UrlMinter",
    "audit_rls",
    "circuit_breaker_key",
    "create_artifact_store",
    "create_database_engine",
    "create_redis_client",
    "create_redis_store",
    "create_s3_client",
    "enum_labels",
    "failure_signature_key",
    "idempotency_key",
    "job_lock_key",
    "jobs_stream_key",
    "lint_migration_script",
    "lint_statements",
    "llm_cache_key",
    "metadata",
    "mint_all",
    "mint_artifact_url",
    "mint_or_null",
    "parse_phase",
    "presign_ttl",
    "progress_key",
    "queue_from_settings",
    "rate_limit_key",
    "require_ttl",
    "sha256_of",
    "spec_for",
    "split_statements",
    "storage_key",
    "tenant_of",
    "tenant_session",
]
